# Generated by Django 3.1.6 on 2021-03-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20210326_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='about_right_richtext',
        ),
    ]
